### ISSUE TITLE
Make a friend?

### ISSUE THREAD

**Issue by OuYang0915** [kitsune7/christopher-bradshaw#1]
I am a web engineer from China,I think you're pretty good,So I want to make friends with you

**Comment by kitsune7** [comment]
Cool! Thanks! Yeah, we can be friends ^_^

**Comment by OuYang0915** [comment]
Can I add your facebook account or twitter account, or do you use WeChat

**Comment by OuYang0915** [comment]
I need to ask you a question on react. It's urgent, please

**Comment by kitsune7** [comment]
I'm on Facebook, you can find me there. An issue on Github isn't the best place to ask if it's not involved with the codebase, but you can message me on Facebook or post a question in StackOverflow and send me a link to it.
